# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FuzzyClone < Formula
  desc "Fuzzy clone is a fuzzy repository picker and downloader, it allows you to quickly jump between repositories you contribute to, whether you have them downloaded or not."
  homepage "https://kasperhermansen.com"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kjuulh/fuzzy-clone/releases/download/v0.1.4/fuzzy-clone-darwin-amd64", using: CurlDownloadStrategy
      sha256 "90f6c1eb41622223be3db9903afd3d0da96eae23e78c69775a5e659d553eb784"

      def install
        bin.install "fuzzy-clone-darwin-amd64" => "fuzzy-clone"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kjuulh/fuzzy-clone/releases/download/v0.1.4/fuzzy-clone-darwin-arm64", using: CurlDownloadStrategy
      sha256 "a4b4ac7a1a86ebd445dd577480dd2640cc37ad47f4cd740b7597b62a1108b41c"

      def install
        bin.install "fuzzy-clone-darwin-arm64" => "fuzzy-clone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kjuulh/fuzzy-clone/releases/download/v0.1.4/fuzzy-clone-linux-amd64", using: CurlDownloadStrategy
      sha256 "3f804402f2d1095d48245871b328f5c7f702810edf0352f55c203a982b423a4b"

      def install
        bin.install "fuzzy-clone-linux-amd64" => "fuzzy-clone"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kjuulh/fuzzy-clone/releases/download/v0.1.4/fuzzy-clone-linux-arm64", using: CurlDownloadStrategy
      sha256 "8dc4b944d36e42535d983998f0d409a2e0e7df9ce4cdd7ab25bd8adb4e8e8f40"

      def install
        bin.install "fuzzy-clone-linux-arm64" => "fuzzy-clone"
      end
    end
  end

  def caveats
    <<~EOS
      Run either fuzzy-clone directory or

      # zsh
      echo 'eval "$(fuzzy-clone init zsh)"' >> ~/.zshrc
    EOS
  end

  test do
    system "#{bin}/fuzzy-clone --version"
  end
end
